### ISSUE TITLE
Mail-Notification

### ISSUE THREAD

**Issue by colin-kiegel** [SuitsU/HelloWorld#3]
Empfänger: Alle Benutzer mit Administrator-Rolle - ILIAS hat dafür einen Verteiler wie folgt: `Administrator <#Administrator@Roles>`

# Minor-Update

Betreff (Sprachvariable): `WICHTIG: Minor-Update verfügbar`
Body
```
Hallo [FIRST_NAME] [LAST_NAME],

für die ILIAS-Installation `[CLIENT_NAME]` (URL: [ILIAS_URL]) ist ein Minor-Update verfügbar!

Regelmäßige Minor-Updates sind eine wichtige Voraussetzung für den sicheren Betrieb von ILIAS. Sie senken damit das Risiko, dass ihr System durch bekannte Sicherheitslücken angegriffen werden kann.

Installierte Version: [[INSTALLED_VERSION]]
Aktuelle Version: [[RELEASE_VERSION]]

Weitere Informationen finden Sie hier:
[[RELEASE_URL]]

---
Dies ist eine Automatische Nachricht des IliasUpdateNotification-Plugins.
```

# Major-Update

.. analog zu oben mit eigenen Platzhaltern, damit wir später unterschiedliche Texte pflegen können.

Dabei sind folgende der o.g. Platzhalter im Mail-System definiert und können über die Funktion "Platzhalter für Serienbrief" automatisch ersetzt werden:
* [FIRST_NAME]: Vorname
* [LAST_NAME]: Nachname
* [CLIENT_NAME]: Name des Mandanten
* [ILIAS_URL]: URL des ILIAS-Systems

Hingegen müsstest du bitte folgende Platzhalter vorher schon ersetzen
* [[INSTALLED_VERSION]] (7.10)
* [[RELEASE_VERSION]] (7.13)
* [[RELEASE_URL]] (https://github.com/...)

---

Zum Vergleich, so sähe es ungefähr aus, wenn man die Mail über die ILIAS-Mail-GUI einpflegt - allerdings wird die Mail dann als Benutzer-Mail statt System-Mail verschickt:

![image](https://user-images.githubusercontent.com/7691186/190916977-80106cdd-0fed-486e-b71d-abe49f886ff6.png)

**Comment by colin-kiegel** [comment]
Dokumentation des Mail-Systems für Entwickler ist hier:

https://github.com/ILIAS-eLearning/ILIAS/tree/release_7/Services/Mail

**Comment by chrisIlias1993** [comment]
Habe Platzhalter eingefügt und den Mailtext angepasst
